_target_: src.models.swin_mae_module.SWINTransformerMAE

image_size: 3072
patch_size: 8 # 16
encoder_stride: 64 # 128
image_channels: 1
mask_ratio: 0.75
compile: true # compile model for faster training with pytorch 2.0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.05
  betas:
  - 0.9
  - 0.95