_target_: src.models.swin_mae_module.SWINTransformerMAE

image_size: 3072
patch_size: 16 # 8
encoder_stride: 128 # 64
image_channels: 1
compile: true # compile model for faster training with pytorch 2.0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.05
  betas:
  - 0.9
  - 0.95

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_start_lr: 1e-5
  warmup_epochs: 5
  max_epochs: 10