_target_: src.models.vit_module.VisionTransformerBodyPartClassifier

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

num_classes: 9 # 9 body region labels

# compile model for faster training with pytorch 2.0
compile: false
