_target_: src.models.vit_module.VisionTransformerBodyPartClassifier

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0
  betas:
  - 0.9
  - 0.95

scheduler:
  _target_: src.optim.warmup_cosine_annealing_lr_scheduler.WarmupCosineAnnealingLR
  _partial_: true
  eta_min: 1e-6
  warmup_steps: 10
  max_steps: 100

compile: false