_target_: src.models.vit_module.VisionTransformerBodyPartClassifier

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.05
  betas:
  - 0.9
  - 0.95

scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  _partial_: true
  factor: 1

num_classes: 14 # 14 bodyparts
compile: false