_target_: src.models.vit_mae_module.VisionTransformerMAE

image_size: 3072
patch_size: 48
image_channels: 1
compile: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.05
  betas:
  - 0.9
  - 0.95

scheduler:
  _target_: src.optim.warmup_cosine_annealing_lr_scheduler.WarmupCosineAnnealingLR
  _partial_: true
  eta_min: 1e-5
  warmup_steps: 2520 # 32276/64*5 = num_train_batches / grad_acc * warmup_epochs
  max_steps: 5040 # = 32276/64*10 = num_train_batches / grad_acc * total_epochs