_target_: src.models.vit_mae_module.VisionTransformerMAE

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01

#scheduler:
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
#  T_max: 5

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 5
  max_epochs: 10

# compile model for faster training with pytorch 2.0
compile: false