# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: "${paths.output_dir}"
  offline: False
  id: null
  anonymous: null
  project: "ma"
  log_model: True
  prefix: ""
  entity: "buehlern"  # Set to your wandb team name
  group: ""
  tags: []
  job_type: ""