defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
#  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  every_n_epochs: 1
  save_top_k: -1
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1

learning_rate_monitor:
  logging_interval: step
  log_momentum: true
  log_weight_decay: true