# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  leave: true
  theme:
    description: ''
    progress_bar: '#6206E0'
    progress_bar_finished: '#6206E0'
    progress_bar_pulse: '#6206E0'
    batch_progress: ''
    time: 'dim'
    processing_speed: 'dim underline'
    metrics: 'italic'
    metrics_text_delimiter: ' '
    metrics_format: '.5f'