_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# mixed precision for extra speed-up
# precision: 16

# set to True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: True # False